# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F_X6KnNS2elB41J2GkBTBkqSKNUE-lzU
"""

a=int(input())
b=int(input())

print(a//b)
print(a/b)