# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1F_X6KnNS2elB41J2GkBTBkqSKNUE-lzU
"""

def is_leap(year):
    
    if year%400==0:
        leap = True
    elif year%100!=0 and year%4==0:
        leap = True
    else:
        leap = False
    
    return leap